version: "3.8"
services:
  db:
    image: mysql
    container_name: j2b_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: j2b_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
  www:
    build: php
    container_name: j2b_www
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:
volumes:
  db-data: