version: '3'

services:
  php:
    container_name: "j2b_php"
    restart: always
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
  nginx:
    container_name: "j2b_nginx"
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "81:80"
  db:
    container_name: "j2b_db"
    build:
      context: ./mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: "j2b_phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
networks:
  dev:
volumes:
  db-data:

